pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        appVersion = ""
    }

    stages {
        stage (' Read Version') {
            steps {
                script {
                        def packageJSON = readJSON file: 'package.json'
                        appVersion = packageJSON.version
                        echo "Version: ${appVersion}"
                }
            }
        }
    }
}