pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        appVersion = ""
    }

    stages {
        stage (' Read Version') {
            steps {
                script {
                        def packageJSON = readJSON file: 'catalogue/package.json'
                        appVersion = packageJSON.version
                        echo "Version: ${appVersion}"
                }
            }
        }
        stage (' Install Dependencies') {
            steps {
                dir('catalogue') {
                    sh """
                        npm install
                    """
                }
            }
        }
        stage (' Build Image') {
            steps {
                dir('catalogue') {
                    sh """
                        docker build -t catalogue:${appVersion} .
                    """
                }
            }
        }
    }
}