pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        appVersion = ""
    }

    stages {
        stage (' Read Version') {
            steps {
                script {
                        def packageJSON = readJSON file: 'catalogue/package.json'
                        appVersion = packageJSON.version
                        echo "Version: ${appVersion}"
                }
            }
        }
        stage (' Install Dependencies') {
            steps {
                dir('catalogue') {
                    sh """
                        npm install
                    """
                }
            }
        }
        stage (' Build Image') {
            steps {
                dir('catalogue') {
                    script {
                        withAWS(region:'eu-east-1',credentials:'aws-creds') {
                                sh """
                                    aws ecr get-login-password --region us-east-1 | docker login --username AWS 
                                    --password-stdin 066899195632.dkr.ecr.us-east-1.amazonaws.com 

                                    docker build 066899195632.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue:${appVersion} .

                                    docker images

                                    docker push 066899195632.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue:${appVersion}
                                """
                        }
                    }
                }
            }
        }
    }
}